### ISSUE TITLE
[Help] Coffee not getting compiled

### ISSUE THREAD

**Issue by joallard** [thisredone/vue-cli-plugin-coffeescript#3]
Hi @thisredone! First off, thank you for making this. It seems like a breath of fresh air among the hours of hell I've spent wrestling with the JS ecosystem bugs.

Everything went well, except I still get syntax errors as if no Coffeescript is being recognized. I'm a bit stumped here.

I'm thinking I'm very close to getting this HelloWorld app up, there must be just one small detail missing. Hopefully I can write a line or two to add to the documentation to help others.

I don't really know what to share to diagnose this, here's my App.vue script tag:
```
<script lang="coffee">
import HelloWorld from "./components/HelloWorld"

export default
  name: "App"
  components: {
    HelloWorld
  }
  computed:
    foo: -> 1
</script>
```

And the resulting error:
![image](https://user-images.githubusercontent.com/949482/79167247-0a162f00-7db5-11ea-8490-3202786b3df9.png)

Anything ring a bell? Thanks!

**Comment by joallard** [comment]
Looks like ESLint is being a problem.

**Comment by thisredone** [comment]
Do you use JavaScript in some of the files as well? Can you disable ESLint and see if the problem is still there?

**Comment by joallard** [comment]
Okay yes, I've finally figured out how to disable eslint:

```
# vue.config.js
module.exports = {
  lintOnSave: false
}
```

I do have `main.js`, I'm not sure whether I'll add some JS or TS later.

Now I notice that errors are in the console instead of with that nice screen. But at least it works!

Do you think it's worth it fixing the lint?

**Comment by thisredone** [comment]
I'm not sure how to keep the ESLint working in this case. If you find a solution for this then I'll accept a PR

**Comment by joallard** [comment]
Okay, thanks for your help!

Maybe we could add this to the Readme, I can make a PR if you'd like:

---

If you're getting compilation errors, ESLint might be getting in the way. One way to solve this is to disable it entirely by editing (or creating) `vue.config.js`:

```
module.exports = {
  lintOnSave: false
}
```

**Comment by thisredone** [comment]
Sure but is this setting enough? Probably uninstalling ESLint plugin works more thoroughly, right?

**Comment by joallard** [comment]
Maybe; I haven't dared mess with it some more now that it was somehow working ;o) 

If you don't feel like that's "up to snuff" enough, that's okay, maybe just leaving this here will help some people if it breaks their setup too.
